
[workspace]
members = [
	'node',
	'pallets/*',
	'runtime/manta',
	'runtime/calamari',
	'runtime/dolphin',
]

[profile.production]
inherits = "release"
codegen-units = 1
lto = true
strip = "symbols"

[profile.release]
panic = "unwind"

[profile.test]
debug = true
