[package]
name = "manta-parachain"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "manta"
path = "src/main.rs"

[dependencies]
derive_more = "0.15.0"
exit-future = "0.1.4"
futures = { version = "0.3.1", features = ["compat"] }
log = "0.4.13"
parking_lot = "0.9.0"
trie-root = "0.15.2"
codec = { package = "parity-scale-codec", version = "=2.0.0" }
structopt = "0.3.3"
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.64"
hex-literal = "0.2.1"

# Parachain dependencies
parachain-runtime = { package = "manta-parachain-runtime", path = "runtime" }
rococo-parachain-primitives = { path = "primitives" }

# Substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }

# RPC related dependencies
jsonrpc-core = "15.1.0"

# Cumulus dependencies
cumulus-client-cli = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", default-features = false }
cumulus-client-consensus-relay-chain = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", default-features = false }
cumulus-client-collator = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", default-features = false }
cumulus-client-service = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", default-features = false }
cumulus-client-network = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", default-features = false }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", default-features = false }

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-test-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }

# orml dependencies
orml-tokens = { path = "../../orml/tokens", default-features = false }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

[dev-dependencies]
assert_cmd = "0.12"
nix = "0.17"
rand = "0.7.3"
tempfile = "3.2.0"
tokio = { version = "0.2.13", features = ["macros"] }

# Polkadot dependencies
polkadot-runtime-common = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-test-runtime = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-test-client = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-test-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }

# Substrate dependencies
pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
substrate-test-client = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
