name: Changelog Verification
on:
  pull_request:
    branches:
      - 'release-**'
  push:
    branches:
      - 'release-**'
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+*'
jobs:
  verify_changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: manta
      - name: Save Dev Local CHANGELOG for diff
        run: |
          cd manta
          sudo cp CHANGELOG.md CHANGELOG_ORIGIN.md
      - name: get Changelog Generator
        uses: actions/checkout@v3
        with:
          repository: Manta-Network/Dev-Tools
          path: dev-tools
      - name: Generate workflow Changelog
        continue-on-error: true
        run: |
          git -C ${{ github.workspace }}/manta fetch
          cd dev-tools/changelog-generator
          cargo b -r
          cargo run -- -u ${GITHUB_ACTOR} ${{ secrets.GITHUB_TOKEN }} \
          -r ${{ github.workspace }}/manta
      - name: Diff changelogs
        run: |
          cd ${{ github.workspace }}/manta
          diff --color -u CHANGELOG.md CHANGELOG_ORIGIN.md
