---

name: publish-release

# yamllint disable-line rule:truthy
on:
  push:
    branches: [manta]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+.*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: ./scripts/init.sh
      - name: build
        run: |
          cargo build --verbose --release -p manta
          strip target/release/manta
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/release/manta
