name: runtime upgrade test
on:
  workflow_dispatch:
    inputs:
      manta_base_url:
        description: The base manta binary url, that will be upgraded
        default: https://github.com/Manta-Network/Manta/releases/download/v4.0.5/manta
        required: true
      polkadot_url:
        description: The polkadot binary url to be used for the relay chain
        default: https://github.com/paritytech/polkadot/releases/download/v0.9.41/polkadot
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  AWS_INSTANCE_SSH_PUBLIC_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPb24HEQ++aNFWaqVyMtIs6GotUB8R+q61XOoI2z6uMj
  AWS_REGION: us-east-1
  AWS_SUBNET_ID: subnet-08c26caf0a52b7c19
  AWS_SECURITY_GROUP_ID: sg-0315bffea9042ac9b
  AWS_INSTANCE_TYPE: c5.9xlarge
  AWS_INSTANCE_ROOT_VOLUME_SIZE: 32
  AWS_IMAGE_SEARCH_PATTERN: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
  AWS_IMAGE_SEARCH_OWNERS: '["099720109477"]'
  POLKADOT_BINARY: ${{github.event.inputs.polkadot_url}}
  MANTA_BINARY: ${{github.event.inputs.manta_base_url}}
jobs:
  print-rust-versions:
    runs-on: ubuntu-20.04
    container:
      image: paritytech/ci-linux:production
    outputs:
      rustc-stable: ${{ steps.get-rust-versions.outputs.stable }}
      rustc-nightly: ${{ steps.get-rust-versions.outputs.nightly }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - id: get-rust-versions
        run: |
          echo "::set-output name=stable::$(rustc +stable --version)"
          echo "::set-output name=nightly::$(rustc +nightly --version)"
  build-runtimes:
    needs: check-for-runtime-upgrade
    runs-on: ubuntu-20.04
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        runtime:
          - name: calamari
          - name: manta
          - name: dolphin
    steps:
      - uses: actions/checkout@v2
      - name: cache target dir
        uses: actions/cache@v2
        with:
          path: "${{ github.workspace }}/runtime/${{ matrix.runtime.name }}/target"
          key: srtool-target-${{ matrix.runtime.name }}-${{ github.sha }}
          restore-keys: |
            srtool-target-${{ matrix.runtime.name }}
      - name: build runtime
        id: srtool-build
        uses: chevdor/srtool-actions@v0.4.0
        with:
          image: paritytech/srtool
          chain: ${{ matrix.runtime.name }}
      - name: persist srtool digest
        run: >
          echo '${{ steps.srtool-build.outputs.json }}' |
          jq > ${{ matrix.runtime.name }}-srtool-output.json
      - if: always()
        name: upload srtool json
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runtime.name }}-srtool-json
          path: ${{ matrix.runtime.name }}-srtool-output.json
      - if: always()
        name: upload runtime
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runtime.name }}-runtime
          path: |
            ${{ steps.srtool-build.outputs.wasm }}
            ${{ steps.srtool-build.outputs.wasm_compressed }}
      - if: always()
        name: upload
        uses: actions/upload-artifact@v2
        with:
          name: config-for-runtime-upgrade-test
          path: .github/resources/config-for-runtime-upgrade-test.json
  runtime-upgrade-test:
    needs: [build-runtimes, start-runtime-upgrade-tester, check-for-runtime-upgrade, parse-runtimes]
    runs-on: ${{ needs.start-runtime-upgrade-tester.outputs.runner-label }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - name: manta
            chain-spec: manta-local
          - name: calamari
            chain-spec: calamari-local
          - name: dolphin
            chain-spec: dolphin-local
    steps:
      - run: |
          ls -ahl ${{ github.workspace }}/
          mkdir -p $HOME/.local/share/${{ matrix.runtime.name }}-pc
          mkdir -p $HOME/.local/bin
          echo "${HOME}/.nvm/versions/node/v16.3.0/bin" >> $GITHUB_PATH
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: fetch, mv and chmod manta-base
        run: |
          wget ${{ env.MANTA_BINARY }}
          ls -ahl ${{ github.workspace }}/
          mv ${{ github.workspace }}/manta $HOME/.local/bin/manta-base
          chmod +x $HOME/.local/bin/manta-base
          ls -ahl ${{ github.workspace }}/
          ls -ahl $HOME/.local/bin/
      - name: fetch and chmod polkadot
        run: |
          curl -L -o $HOME/.local/bin/polkadot ${{ env.POLKADOT_BINARY }}
          chmod +x $HOME/.local/bin/polkadot
          ls -ahl $HOME/.local/bin/
      - id: create-chainspec
        run: |
          manta-base build-spec --chain ${{ matrix.runtime.chain-spec }} --disable-default-bootnode --raw > $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-spec.json
          jq \
            --sort-keys \
            --arg name "${{ matrix.runtime.name }} testnet base" \
            --arg id ${{ matrix.runtime.chain-spec }}-base \
            --arg relay_chain rococo-local-base \
            '. |
              .name = $name |
              .id = $id |
              .relay_chain = $relay_chain |
              .telemetryEndpoints = [["/dns/api.telemetry.manta.systems/tcp/443/x-parity-wss/%2Fsubmit%2F", 0]]
            ' $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-spec.json > $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-spec.json
          ls -ahl $HOME/.local/share/${{ matrix.runtime.name }}-pc/
          manta-base export-state --chain $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-spec.json > $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-state.json || true
      - name: fetch config-for-runtime-upgrade-test
        uses: actions/download-artifact@v2
        with:
          name: config-for-runtime-upgrade-test
      - name: create launch config
        run: |
          ls -a
          cat config-for-runtime-upgrade-test.json | \
          jq \
            --arg relaychain_bin $HOME/.local/bin/polkadot \
            --arg relaychain_id rococo-local-base \
            --arg relaychain_name "rococo local base" \
            --arg parachains_bin $HOME/.local/bin/manta-base \
            --arg parachains_spec $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-spec.json \
            '.
              | .relaychain.bin = $relaychain_bin
              | .relaychain.mutation.id = $relaychain_id
              | .relaychain.mutation.name = $relaychain_name
              | .parachains[].bin = $parachains_bin
              | .parachains[].chain = $parachains_spec
            ' > $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-launch-config.json
          jq . $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-launch-config.json
          ls -ahl $HOME/.local/share/${{ matrix.runtime.name }}-pc/
      - uses: actions/checkout@v2
        with:
          repository: paritytech/polkadot-launch
          path: polkadot-launch
      - uses: actions/checkout@v2
        with:
          repository: Manta-Network/Dev-Tools
          path: dev-tools
      - name: launch testnet
        run: |
          cd ${{ github.workspace }}/polkadot-launch
          yarn install
          yarn build
          pm2 start dist/cli.js \
            --name polkadot-launch \
            --output ${{ github.workspace }}/polkadot-launch-for-${{ matrix.runtime.chain-spec }}-stdout.log \
            --error ${{ github.workspace }}/polkadot-launch-for-${{ matrix.runtime.chain-spec }}-stderr.log \
            --no-autorestart \
            -- $HOME/.local/share/${{ matrix.runtime.name }}-pc/${{ matrix.runtime.chain-spec }}-base-launch-config.json
      - name: fetch new ${{ matrix.runtime.name }}_runtime.compact.compressed.wasm
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.runtime.name }}-runtime
      - uses: actions/checkout@v2
        with:
          repository: Manta-Network/Manta
          path: Manta
      - name: run test suites
        run: |
          sleep 120
          cp ${{ github.workspace }}/${{ matrix.runtime.name }}_runtime.compact.compressed.wasm ${{ github.workspace }}/Manta/tests/calamari.wasm
          cd ${{ github.workspace }}/Manta/tests
          yarn install
          yarn
          yarn runtime_upgrade_test --address=ws://127.0.0.1:9921 --exit
          if [ $? != 0 ]; then echo "Runtime upgrade failed!"; exit 1; fi
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.chain-spec.id }}-alice.log
          path: ${{ github.workspace }}/polkadot-launch/9921.log
  # HELPER JOBS BELOW
  start-runtime-upgrade-tester:
    runs-on: ubuntu-20.04
    outputs:
      runner-label: ${{ steps.start-self-hosted-runner.outputs.runner-label }}
      aws-region: ${{ steps.start-self-hosted-runner.outputs.aws-region }}
      aws-instance-id: ${{ steps.start-self-hosted-runner.outputs.aws-instance-id }}
    steps:
      - id: start-self-hosted-runner
        uses: audacious-network/aws-github-runner@v1.0.33
        with:
          mode: start
          github-token: ${{ secrets.SELF_HOSTED_RUNNER_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-instance-ssh-public-key: ${{ env.AWS_INSTANCE_SSH_PUBLIC_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          aws-subnet-id: ${{ env.AWS_SUBNET_ID }}
          aws-security-group-id: ${{ env.AWS_SECURITY_GROUP_ID }}
          aws-instance-type: ${{ env.AWS_INSTANCE_TYPE }}
          aws-instance-root-volume-size: 64
          aws-image-search-pattern: ${{ env.AWS_IMAGE_SEARCH_PATTERN }}
          aws-image-search-owners: ${{ env.AWS_IMAGE_SEARCH_OWNERS }}
  stop-runtime-upgrade-tester:
    if: ${{ always() }}
    needs: [runtime-upgrade-test, check-for-runtime-upgrade, start-runtime-upgrade-tester]
    runs-on: ubuntu-20.04
    steps:
      - continue-on-error: true
        uses: audacious-network/aws-github-runner@v1.0.33
        with:
          mode: stop
          github-token: ${{ secrets.SELF_HOSTED_RUNNER_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ needs.start-runtime-upgrade-tester.outputs.aws-region }}
          runner-label: ${{ needs.start-runtime-upgrade-tester.outputs.runner-label }}
          aws-instance-id: ${{ needs.start-runtime-upgrade-tester.outputs.aws-instance-id }}
      - name: discard stopper success/failure
        run: true
